README.md, app/templates/components/fixtable-grid.hbs, package.json, tests/dummy/app/routes/index.js, tests/dummy/app/styles/_colors.scss, tests/dummy/app/styles/_fixtable.scss, tests/dummy/app/styles/app.css, tests/dummy/app/styles/app.scss, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/index.hbs
This adds the specified CSS class(es) directly to the table element. I also updated the styles of the dummy app's {{fixtable-grid}} to demo the 'tableClass' property.
=> Add support for 'tableClass' property

app/templates/components/fixtable-grid.hbs, vendor/styles/fixtable-ember.css
Message is shown when 1) there are no rows to be shown, and 2) the loading indicator is not being shown. Fix to issue #22.
=> Show a "No data available" message

addon/components/fixtable-grid.js, app/templates/components/fixtable-grid.hbs, vendor/styles/fixtable-ember.css
Disable the previous pager button on the first page. Disable the forward pager button on the last page. Change page input to number-type.
=> Disable pager buttons when appropriate

addon/components/fixtable-grid.js
I renamed filteredContent -> sortedFilteredContent and missed updating the totalRows computed property. This broke client pagination. Should be fixed with this commit.
=> Update totalRows computed property to rely on sortedFilteredContent

addon/components/fixtable-grid.js, package.json
NotifyReloadContent will call the registered onReloadContent handler thus triggering a data load on initial page load. This is significant for server paging to trigger the initial call to the api with the correct values for page and pageSize.
=> load data on first page load

blueprints/fixtable-ember/index.js, bower.json, index.js, package.json
Moving font-awesome from being loaded by bower to being loaded by npm.  
The internal ember addon for purecloud apps, ember-purecloud-components, loads font-awesome via npm in a similar way to this PR.  When importing through bower we get an error because both the npm and bower imports put the fonts in the /vendor/fonts directory.  While we can specify { overwrite: true } when merging npm files, we have no control over the bower merge.  
So the change here is to move away from using bower and bring in font-awesome through npm.  Ember is moving away from requiring bower as a dependency, so I think this is a good long term update, as well as fixing the conflict issue we are facing.
=> Load font awesome from npm

package.json
One more update to get this change working in an engine consuming app.  Need to make font-awesome a dependency as opposed to a devDependency, so that it gets installed under its parent's node_modules. Otherwise you get the following error: Error: `ENOENT: no such file or directory, scandir '/Users/jordanto/dev/inin/web-directory/node_modules/ember-engine-admin-vr/node_modules/font-awesome/fonts'`
=> make font-awesome a dependency

addon/components/fixtable-footer.js, addon/templates/components/fixtable-footer.hbs, addon/templates/components/fixtable-grid.hbs, app/components/fixtable-footer.js, tests/integration/components/fixtable-footer-test.js
No functional difference; just a small refactoring to reduce the size of the fixtable-grid component.
=> Extract footer markup into a separate component

addon/components/fixtable-grid.js
Fix to #64. Should defer Fixtable initialization enough to prevent the warning about setting properties in `didInsertElement`.
=> Defer fixtable initialization

addon/templates/components/fixtable-grid.hbs, package.json
Hides pagination footer when we show the "no data available" message -- e.g., when no data is loaded at all or the filter conditions exclude all of the rows. This prevents showing weird things like "page 1 of 0" and doesn't remove any functionality since you can't page backwards/forwards if there's no data, anyway.
=> Hide pagination footer when there's no visible content

.gitignore, README.md, addon/templates/components/fixtable-grid.hbs, tests/dummy/app/routes/index.js, tests/dummy/app/templates/index.hbs
The placeholder option that you specify will set the `placeholder` attribute of the input helper for the 'search' type and will be used for the label of the default option for the 'select' type.
=> Add a placeholder option to the column filter options

README.md, addon/components/fixtable-grid.js, addon/templates/components/fixtable-grid.hbs, tests/dummy/app/controllers/editable.js, tests/dummy/app/controllers/index.js, tests/dummy/app/templates/editable.hbs, tests/dummy/app/templates/index.hbs
This PR changes the row selection handler so that it returns full selected data rows to the consumer, rather than indices into the visible content. (For client filtered/paginated rows, there's simply no easy way for the consumer to know what's in the visible content, which makes the row selection API practically worthless.) Fixes issue #87.
This PR causes breaking changes to the row selection API, so it will require a major version bump to adhere to semver. In particular, these two things have changed:
* The signature of the row selection handler
* When the row selection handler is called (now it's also called whenever onReloadContent is called, instead of requiring the consumer to monitor both events if they only care about selection)
=> Restore sanity to the row selection API

addon/components/fixtable-grid.js, addon/templates/components/fixtable-grid.hbs, package.json
Removed our dependency on ember-truth-helpers. Because this addon is commonly used in other addons/engines, it's preferable for us to minimize dependencies that might conflict (in version) with those of the parent app.
=> Remove ember-truth-helpers dependency

index.js
using `this.import` is the preferred way of importing dependencies, especially when nesting addons.  I'm hoping that this fix will help some of our font awesome dependency issues in our consuming app (web-directory)
see https://github.com/ember-cli/ember-cli/pull/5877
=> change from using app.import to this.import

index.js
require.resolve leverages npm logic to locate packages, so this should get us out of the business of trying to recursively find the location of packages.
This fix superscedes
https://github.com/MyPureCloud/fixtable-ember/pull/101
cc @omarestrella
=> Use require.resolve for locating assets

README.md, addon/components/fixtable-grid.js, package.json
Changes made in v3.2.0 caused visibleContent computed property to encounter a JavaScript error if the fixtable-grid was supplied any value that wasn't an Array or Array-like object. This has been hardened to ensure that the supplied content is a supported type, and outputs a warning if not. The README has also been updated to make this type requirement explicit.
=> harden visibleContent property against being passed a non-array

package.json
This was breaking web-directory when we pick up the latest versions (^3.2.1).  When you put a package in "dependencies" it pushes the provided version onto consuming apps.  In the case of web-directory, we want it to be ~2.14, but since this dependency is ^2.12, it was causing web directory to pick up version 2.15 (latest), causing a breaking change in the app. If you move to devDependencies it lets the consuming app to control the version.
=> move ember-data to devDeps bc it forces latest on app

README.md, addon/components/fixtable-grid.js, package.json
Adds support for externalFilters property which fixtable-grid component will observe for changes. Triggers a reload just as if one of the column filters was updated.
=> External filters

index.js
so linting tools, such as ember-cli-template-lint rely on `isDevelopingAddon` to decide whether to lint addon code.  Seems in recent ember cli releases that it decides that because fixtable does not implement that method, then it will assume "yes" to linting.  We don't want our implementors to have this forced on them, so I'm giving it a default implementation of `false`, and addon developers can change it to true when developing new features.
Currently breaking the web-directory app
=> add isDevelopingAddon implementation

addon/components/fixtable-grid.js
fix an error when running with two fixtable tables in ember test where jquery is unable to find the fixtable element initially
=> fix an error when running with two fixtable tables in ember test
